server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://cstnpkdumphs73frmh70-a.oregon-postgres.render.com:5432/users_lxtq
    username: users_lxtq_user
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

  sql:
    init:
      schema-locations: classpath:/schema-postgresql.sql
      mode: always
      platform: postgres
