server:
  port: 8080

spring:
  config:
    import: "classpath:/application.yaml,optional:classpath:/application-env.yaml"
  profiles:
    active: env
  datasource:
    url: jdbc:postgresql://dpg-cstp9maj1k6c73efp4ag-a.oregon-postgres.render.com:5432/users_wtgl
    username: users_wtgl_user
    password: 1gZSjO14nqxKAAsZGeDM2pIyHUBfIspw
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

  sql:
    init:
      schema-locations: classpath:/schema-postgresql.sql
      mode: always
      platform: postgres
